apiVersion: v1
kind: Secret
metadata:
  name: devops-secret
type: Opaque
data:
  username: YWRtaW4=
  password: YWRtaW4xMjM=
# to decode echo -n "YWRtaW4xMjM="| base64 --decode
# echo -n "admin123"| base64 to encode
